x_timegrid = linspace(-1,1,200);

hyper = make_hyper();

mixture = nhgpmixture(3, ...
                      x_timegrid, ...
                      hyper.mu_m, hyper.G_m, hyper.L_m, ...
                      hyper.mu_loggamma, hyper.G_loggamma, hyper.L_loggamma, ...
                      hyper.mu_loglambda, hyper.G_loglambda, hyper.L_loglambda, ...
                      hyper.mu_logeta, hyper.G_logeta, hyper.L_logeta, ...
                      hyper.tol);

