function LL = logG0pdf(hyper, m, loggamma, loglambda, logeta)
    T = length(m);
	LL = logmvnpdf(m', zeros(1,T), hyper.Km, hyper.invKm) + ...
         logmvnpdf(loggamma', hyper.mu_loggamma*ones(1,T), hyper.Kloggamma, hyper.invKloggamma) + ...
         logmvnpdf(loglambda', hyper.mu_loglambda*ones(1,T), hyper.Kloglambda, hyper.invKloglambda) + ...
         logmvnpdf(logeta', hyper.mu_logeta*ones(1,T), hyper.Klogeta, hyper.invKlogeta);
end

